repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [check, --fix]  # Run ruff check with the --fix option
      - id: ruff
        args: [format]  # Run ruff format
